apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
  namespace: renovate
spec:
  schedule: '@midnight'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: renovate/renovate:38.128.6
              command: ["/bin/sh","-c"]
              args: ["cd /opt/renovate && cat /opt/renovate/config.json && renovate"]
              name: renovate-bot
              env:
                - name: RENOVATE_BASE_DIR
                  value: '/tmp/renovate/'
                - name: RENOVATE_CONFIG_FILE
                  value: '/opt/renovate/config.json'
                - name: LOG_LEVEL
                  value: debug
              volumeMounts:
                - name: config-volume
                  mountPath: "/opt/renovate/config.json"
                  subPath: config.js
                  readonly: true
                - name: work-volume
                  mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
            - name: config-volume
              secret:
                secretName: renovate-config
                items:
                  - key: config.js
                    path: config.js
            - name: work-volume
              emptyDir: {}
