apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: renovate
spec:
  encryptedData:
    TokenSecret: AgBva6yC0tV8SUmVWq6KZkGSZpggxNMWwbEfW929n3byt0oNp+OSZQWPk7CVfzspd44zTU5VHTr+Y45KLwuHjhCKQB2sZb84sORLaFuJ9qXFeliFrTlf/sF7PQqx1yVyAxaHYDJPqpB7qoVQCBAe3/hcWbmr0TW+Pc2/QcYH2j7MVnfKmhFIFoE5X5V3JVhtb7uaf7JsPIi2de40jm3GITxXjypQntwwoq2xJ7wjtdogZDlScIsG26qkYtXZnYWd2Zskyu0/Luhv2D99NEXTRrixMHqeCmcv/InbtSZC7iYfFMqpJLAVjFvZDbYmCE135KccdlqYUWgbsMH/kusCAltt0nR/gJe8ezJHlyiWju3OUIH5ZisXMXMgqUuIXERSgIZxMF9GbXjutCBesRplteIIIMtGKllCltVvSskN+gdj7UXLb3bzYRTNFF2+DpQtZl0kIfIrVZbbiMv/SR6eOmretlPjWcNifqDI25nDzMSQ+UMZFHidUtiSP1X+qCUiSPNQ3pUCCLPd93huyXtjOHAtMwL7ZWWC+jo1IDuMo/V6m45dkuZd0yY7sJ6EKZfi6eP15QYuwm/YFNXmjxG/COnNt49vT6ZPCzusnCFFoMy2YnlosIP5+EvM1z1Em4WhhmHtQMem78TQyUSiw4QeE3+UwPNCmM8hB4ngFZbxBeIlhY0e85bu2NJggvVjGRSrm3Wd4EoxnxRMGPBwepz1Dc9F3hJDBIbDqi8Bcttuo1xwvkWFeAtKn85S1DM/idjnl4DstDTU61silh5TcGpfX/U7qCQwxkF1jX6gczoYrhkuOHG8HL5YJrhb3MLGJEE=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-config
      namespace: renovate
    data:
      config.js: |
        [module.exports = {
            platform: 'github',
            //dryRun: 'full',
            token: '{{ index . "TokenSecret" }}',
            repositories: ["zunin/fleet"]
        }


