apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: renovate-config
  namespace: renovate
spec:
  encryptedData:
    TokenSecret: AgBV8sFSlf8+HXrhAb7C3FeUXaoYhqjb4U1HkuZxUnapg0WfR6SjL0qD34kKHVNwMxTgG+V/8TzJ26diI075VWktjE/lpENWKR3tvf9R/3roMA50u8Zb9dGLwM1rcGNa0V6macHZWm31hEKt5yal4JlF8g7nDwNoE5e9y1EDbFEX5ZgAM5ziNxxnlTc2Om3LD7S5OnU1set3bTwpDIl4CXpJSBQx2yN7KWvuuCQT6W5D2Ie3LWxHvnJWbeZtnqvCAgjGFX9IOF/o2SYTv9EgKE6EkasVpJUZvTsjzd9737SkL0b1KYKuQSv/5zzb6uBxyC3TiYD/l0v/wjHKnxHdE4bEhBDa9Hayb9GadEZiofaz3a9pas9LADcKsMOhRYggd5EaRl/hF1DIyQb6F/8KyrtU+ugoXKMCHgZxrXRe5NtqSEwir5g+pNRVeJVEznKSuc2N0w6Vi67FkOFJJnoLwT5CwRD0+4GEtiUxTh0cZG5d6Zq5ILbzpFTIoGIr5EJtscXCWEfxGxp8SK+JPQ93q1aE4Qnf886jh6xdd2GSnHwaajVcfPgF+uclgHhX1xepAnFLUfzO58di4MxIUYWBPnBFT+tH/uC1NCbmvZTQpds2q5ObI92msS7d75/mhiFiRJ11/CXlr9DJ2wAkmauRieMirlPdnM2E00dd2pUnhU7eNXcCY9j6AwdIGfvdY1T3zIBUAnCSC3LVC4N+5A6aEHZXvIgITYsoYDHv19u3YSe4veIdrGoRvrin8LupdKp67bdYBXhjId0Yk+Y5G7GthCVMu7m5DZ2rJYneOVkyvhhFakxOB+b9fyJb3/jpaiY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: renovate-config
      namespace: renovate
    data:
      config.js: |
        {
            platform: 'github',
            token: '{{ index . "TokenSecret" }}',
            repositories: ["zunin/fleet"]
        }


