apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-config
  namespace: renovate
spec:
  encryptedData:
    TokenSecret: AgCcjrOsxfFaqOrfCgwg57fjKlQ10AVbum/AwrpsXaaUJy8AqIyidyC4S9J3OYgb3QdCFfdv35pgoumWeFcaVcjOiruQl07GwASrPBleRnKft3hLCGuhpavePivzqH8p1UF26Oxg9GmUL7OyfBeZoJ8RLi1pLWV5UF5XI3aIbD+7KohiCc2TD9nNKVYzr+x4DoaWt5kQG0Hkxndrs82g89PVoIjgv9Iicv+C89qRTfd6dZWdh+PLlmp8TJH7710muN0DEHigVXpCzTO8W28nxdWavDsb2rXxVbjJpR32venfJNnbK1opKHAAAv0mDyqYaoMbuwy2dgyY2dxvMVajxg6Xt67Ipi8qYgVari7SnjZcrSbxbwQN6sHjACP4i8H48umYSoCfp6/P4RNzmIefPZjd7rwg+GwyVWVAPyo26SiD+bONSUGhIZ1uM9oRugbahSnpIxU8Ixaj1OmXSVrRypI73Xxomvyw+UEb+OqAyZSaoExa4mx84aE4vyrwEFof+emnAnLaaPGsSMtght0kC63T/jdXyLSLjYyHWxb05HTSQq9QfV/3BrQpcClKcPc4FJcv+23yscqo+9cfUubS6xD5k6cOwrjWrlCVAd8UYv2qt2XxnmwwA7E12UeGGCtYi0IrxhJqSMzApUfGOAVHOX02Ix8S1O4wMOXfOnOKciLes4yAgGpLwAAS8aQ40mDsSmPTL+pOourZyUpcI6lZLqUbhBfudzm9JguAoFyi8SVsy+/Mpx2U2CYl4ar5mFaYsW1fTvUn52zewY5Nkh/sQr74IH2hRJLI87/9MybFZPbmvxSnOEvcKVyVLwL0ZPw=
  template:
    metadata:
      creationTimestamp: null
      name: renovate-config
      namespace: renovate
    data:
      config.js: |
        [module.exports = {
            platform: 'github',
            //dryRun: 'full',
            token: '{{ index . "TokenSecret" }}',
            repositories: ["zunin/fleet"]
        }


