apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: renovate-config
  namespace: renovate
spec:
  encryptedData:
    TokenSecret: AgBQrzaSAYsAQDQeSkayPFZuitvNv1zrAK3J/kgVKtbi5b7sD3Q8U2qb+rwbnbzWfBw5tv0uyaSOPM6+VwR/6igcdrznk0FRosKZMhnioc9duE3d2heueh/N1UEP1cehIxWWIZZ95h1AXMFmKHQE+aHeZotwJop5nGTeGorv25F9nCnAnQLFwbTmhX0YlDP7HW3r0E7kg4cZkoNfUCuAPEa+Pf61ecjOkpw7GswNa6LXrHvMkCYg7EiDlG/OgFyEC7CZEgEWnWyLh2td0m6/GyVlbp9CzZnplKV4P+tSNbtLm4+DZWVL5nCtK1ERtZ6X7QnbXMud8hwlHnF69tb/bnFZkEjcNldjXxNfhH+C+ZNba2SbvDtOayHrPxYgLfJd9Pw/kTGfGITIjbOz1gsp2/EZ1JlT6X/Y3BmDqv6R7HV7yQ4jzpTtVy8Aq+3YC8xKPMlYZQZkkKXs1/MW1gVz2u1w5EAbQxhOv8BNdnV/v27MNiVPQgHrV1tWz0kvca66RzSyziVpn3BqhpHrH3IpPaXvqbWLNn97tQ+a6X/PUT4s/OVo9f0FW9qmku3pZS9ndIQJbMP6whFzSBWUoOQCV/wOS/02XECatD1Q2NCIwg2E0y+V0/hrshG8NFTM1wFjd+ULQCQOs4DqwBsRtuZGX+fXkWXYDr7MtNL0lNFtbOuiAvHvBDgVwYrDz/LiPYC1TeHuSj0Li+9brTOXDJGoQsBuZ3rMfXTKOON/F+VqZi20jdznWOEKhNmxKFpVqRFfgq2NEgUH8tomAgv+5S9Jj5zkxW7sSrKkKqN4cxyQzQBqSVAS6xqlf0I8v2qsKrA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: renovate-config
      namespace: renovate
    data:
      config.js: |
        {module.exports = {
            platform: 'github',
            token: '{{ index . "TokenSecret" }}',
            repositories: ["zunin/fleet"]
        }


