apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibreweb-books
  namespace: books
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/app: books
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
