apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: books
  namespace: books
spec:
  name: books
  namespace: books
  container:
    image: crocodilestick/calibre-web-automated
    tag: latest
    port: 8083
  url: "books.nikolaiathome.com"
  localUrl: "books-copyparty.local.nikolaiathome.com"
  replicas: 1
  ingress:
    enabled: true
  externalVolumes:
    - name: config
      persistentVolumeClaim: calibreweb-config
      containerMountPath: /config
    - name: books
      persistentVolumeClaim: calibreweb-books
      containerMountPath: /calibre-library
    - name: ingest
      persistentVolumeClaim: calibreweb-ingest
      containerMountPath: /cwa-book-ingest
  env:
    TZ: "Europe/Copenhagen"
    PUID: "1000"
    PGID: "1000"
  filebrowser:
    enabled: true
    port: 3928
  resources:
    memory: "512Mi"
    cpu: "0.5"
  runAsUser: 0
  runAsNonRoot: false
  livenessProbePath: "/"
  readOnlyRootFilesystem: false
