apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: books
  namespace: books
spec:
  name: books
  namespace: books
  container:
    image: jvmilazz0/kavita
    # renovate: datasource=github-releases depName=Kareadita/Kavita
    tag: 0.9.0.2
    port: 5000
  url: "books.nikolaiathome.com"
  localUrl: "books-copyparty.local.nikolaiathome.com"
  replicas: 1
  ingress:
    enabled: true
    websocketRoutes: "/"
  externalVolumes:
    - name: config
      persistentVolumeClaim: kavita-config
      containerMountPath: /kavita/config
    - name: media
      persistentVolumeClaim: kavita-media
      containerMountPath: /media
  env:
    TZ: "Europe/Copenhagen"
  filebrowser:
    enabled: true
    port: 3928
  resources:
    memory: "512Mi"
    cpu: "0.5"
  runAsUser: 1000
  runAsNonRoot: true
  livenessProbePath: "/"
  readOnlyRootFilesystem: false
