apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibreweb
  namespace: books
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre-web
      version: 9.0.2
      sourceRef:
        kind: HelmRepository
        name: k8s-home-lab
        namespace: books
  values: 
    appVersion: 0.6.23
    image:
      repository: ghcr.io/linuxserver/calibre-web
      # renovate: datasource=github-releases depName=linuxserver/docker-calibre-web
      tag: "0.6.23-ls294"
    env:
      TZ: "Europe/Copenhagen"
    ingress:
      main:
        enabled: true
        hosts:
          -  # -- Host address. Helm template can be passed.
            host: books.nikolaiathome.com
            - path: /
                pathType: Prefix 
    persistence:
      config:
        enabled: true
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
      books:
        enabled: true
        mountPath: /books
        accessMode: ReadWriteOnce
        size: 10Gi

