apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibreweb
  namespace: books
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: books
  values: 
    appVersion: 0.6.23
    controller:
      type: statefulset
    image:
      repository: ghcr.io/linuxserver/calibre-web
      # renovate: datasource=github-releases depName=linuxserver/docker-calibre-web
      tag: "0.6.23-ls294"
    service:
      main:
        ports:
          http:
            port: 8083
    ingress:
      main: 
        enabled: true
        hosts:
          - host: books.nikolaiathome.com
            paths:
              - path: /
                pathType: Prefix 
    env:
      TZ: "Europe/Copenhagen"
    persistence:
      config:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 2Gi
      books:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 10Gi

