apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-data
  namespace: search
  labels:
    name: search-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
