apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: search-data
  namespace: search
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/app: hister
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
