---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: extraConfig
  namespace: chat
spec:
  encryptedData:
    client_secret: AgAADYs107jgiFnRVgkZjkcOd0WCdtR5dnaazh+pSPFvG63GDEEuIE8GqX1TNSOaR3lDroBKP9ZQTh4EVijCW5CcMI3u+Ggt8oiwKD5clNiEcHgzV841gicHCBPZHZA7WHk7BTGpcNgie245RGXERU4i6BoWMm99w75vKb4S4I97T6FsNd8ZF+LPC6suB3yb/743Q6bCaDvH4PabM+VcwAoPOwWspcCSz+2aOsD+VPGlqA+9myv612suqYSvSdd0w2BNWArJjxutp4QicHr8n8IBo8oEld+uYZonGSRAHXYucMcHYjMyZtmAggPF2V4k/5J2PmM/a0REbMabPu1lv7ySqRTQK1aeSxVHCz9snt7TqZlxENqC899lXk/E2M0whC1Y1uZvduovahFPgOQLV26w+alaRywzUwJZFfESL6aBfEmvoSwDwQAYpc4XJ4K2mv4OhjkZH4zaMakAPPY5DB9Cx5EHnuR4EdYDMq/fBclDBPmHE8gqxi721WrPAFxcZlHft8aRxJJfffLaSa+vOszO8paa4Hz+kLZrhwgzwVpiniA1DJpieK9MCH3T6JB9UWWA7xj/xUpYNdw+pCM3VshEsKy8kOeOZauv3nEZCIo//PpjjQSt0gqEIZwxplPAxp0V2JxCqKi2nceI8SZBkON+h1fxJkLqGc835qvjeXxOxPC2ZRnSyTyfHhBXWs/A8K59M9daSjBYTbAfO4vp3hO08L0l0ZIYbfz4DX084FJdCFCADSOyB2FtzNu+3cAysQuRwK1yxXGzA1fQpTB4611Q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: extraConfig
      namespace: chat
    data:
      oidc_providers:
      - idp_id: oelleguard
        idp_name: Ølleguard
        discover: true
        issuer: https://auth.nikolaiathome.com
        authorization_endpoint: https://auth.nikolaiathome.com/oauth/v2/authorize
        token_endpoint: https://auth.nikolaiathome.com/oauth/v2/token
        userinfo_endpoint: https://auth.nikolaiathome.com/oidc/v1/userinfo
        client_id: 214037595124990002@nikolaiathome
        client_secret: {{ index . "client_secret" }}
        backchannel_logout_enabled: true
        scopes:
          - "openid"
          - "profile"
          - "email"
