---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: extraconfig
  namespace: chat
spec:
  encryptedData:
    client_secret: AgAADYs107jgiFnRVgkZjkcOd0WCdtR5dnaazh+pSPFvG63GDEEuIE8GqX1TNSOaR3lDroBKP9ZQTh4EVijCW5CcMI3u+Ggt8oiwKD5clNiEcHgzV841gicHCBPZHZA7WHk7BTGpcNgie245RGXERU4i6BoWMm99w75vKb4S4I97T6FsNd8ZF+LPC6suB3yb/743Q6bCaDvH4PabM+VcwAoPOwWspcCSz+2aOsD+VPGlqA+9myv612suqYSvSdd0w2BNWArJjxutp4QicHr8n8IBo8oEld+uYZonGSRAHXYucMcHYjMyZtmAggPF2V4k/5J2PmM/a0REbMabPu1lv7ySqRTQK1aeSxVHCz9snt7TqZlxENqC899lXk/E2M0whC1Y1uZvduovahFPgOQLV26w+alaRywzUwJZFfESL6aBfEmvoSwDwQAYpc4XJ4K2mv4OhjkZH4zaMakAPPY5DB9Cx5EHnuR4EdYDMq/fBclDBPmHE8gqxi721WrPAFxcZlHft8aRxJJfffLaSa+vOszO8paa4Hz+kLZrhwgzwVpiniA1DJpieK9MCH3T6JB9UWWA7xj/xUpYNdw+pCM3VshEsKy8kOeOZauv3nEZCIo//PpjjQSt0gqEIZwxplPAxp0V2JxCqKi2nceI8SZBkON+h1fxJkLqGc835qvjeXxOxPC2ZRnSyTyfHhBXWs/A8K59M9daSjBYTbAfO4vp3hO08L0l0ZIYbfz4DX084FJdCFCADSOyB2FtzNu+3cAysQuRwK1yxXGzA1fQpTB4611Q
    signing_key: AgBHfIRGjgsqGx49kXgzeJyFJ3wyvO2jTacz1sH6FFK/jqtnLtvZVHc/kns9+XFSatj+EilCT04HDtrd3pjWbvsPzLLFbwiKNPI5G2a9a+WGYYqYUDmXVjiUCXuPhwpQAu7uoaxa9Rtdy1Zt8GFboCCeXcdKxH09iFOiqwQLcWvE9le++HPRMVFfrviqtRaT23u+0ieikUis9B6+r8N3WJtbh7DzL90mJgev5959bj3Qr+ZAKKOEB8VkuveZUUSeByKQDdObJbahiYeJ732WTjEeeqajIjMzqrGPWWQ5/DC5mVCvB59QSW8hVuLaHHF4ZZpbviYwT9Bl01nCM2BmzBX96MphUAKxhJWObEYmS5QaHJJuhvKw9z9d7jeSAMZItn2HJ3StOKgVwEzZnWJSrJVPM7C6XkQXlqb1hyT2k1NkXCDXjOUkC8HE6DNx0nYUPFJ413UshkyAv8wY86NKlGN8pPFCtXotkWx68aFJK7UAuv/P41SLV7TvnYuyt6egGwV3gkcppxjABFpQatgSSduyof5iNv2+Jg8DsaVqy+6haS8mmUFOb1Oi5H1dexjhE2o3X9kN+U5UnIU0/hJjDpz0HjMtHUkB8pXVOgWk5zO+4BJXlAkLMjT04EV4nlTa0PgBmBOrrlPI7uXQEKXDYrUa1xHvDKni07wRs9lDk8cOFXrJ3ADrwNmdhSCRZd5K+m2XcCofo4Wlw7e2ksNzQwvYX2fTKH0ZvunA+RlcUNaLEi/2V2pLVyY14FqyB3UFsfBVnVBzrFBkxXK/EsrMfRs8Fzd1ISXUT2FAoHumSrZyew==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: extraconfig
      namespace: chat
    data:
      extraConfig: |
      max_upload_size: 100M
      old_signing_keys:
        "ed25519:a_LVFo":
          "key": "n+22pBNkpWGAqTyPyk/yZlHx8uHm6O2r2OdekMe/b/g"
      oidc_providers:
        - idp_id: oelleguard
          idp_name: Ølleguard
          discover: true
          issuer: https://auth.nikolaiathome.com
          authorization_endpoint: https://auth.nikolaiathome.com/oauth/v2/authorize
          token_endpoint: https://auth.nikolaiathome.com/oauth/v2/token
          userinfo_endpoint: https://auth.nikolaiathome.com/oidc/v1/userinfo
          client_id: 214037595124990002@nikolaiathome
          client_secret: {{ index . "client_secret" }}
          backchannel_logout_enabled: true
          scopes:
            - "openid"
            - "profile"
            - "email"
