---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: extraconfig
  namespace: chat
spec:
  encryptedData:
    client_secret: AgAADYs107jgiFnRVgkZjkcOd0WCdtR5dnaazh+pSPFvG63GDEEuIE8GqX1TNSOaR3lDroBKP9ZQTh4EVijCW5CcMI3u+Ggt8oiwKD5clNiEcHgzV841gicHCBPZHZA7WHk7BTGpcNgie245RGXERU4i6BoWMm99w75vKb4S4I97T6FsNd8ZF+LPC6suB3yb/743Q6bCaDvH4PabM+VcwAoPOwWspcCSz+2aOsD+VPGlqA+9myv612suqYSvSdd0w2BNWArJjxutp4QicHr8n8IBo8oEld+uYZonGSRAHXYucMcHYjMyZtmAggPF2V4k/5J2PmM/a0REbMabPu1lv7ySqRTQK1aeSxVHCz9snt7TqZlxENqC899lXk/E2M0whC1Y1uZvduovahFPgOQLV26w+alaRywzUwJZFfESL6aBfEmvoSwDwQAYpc4XJ4K2mv4OhjkZH4zaMakAPPY5DB9Cx5EHnuR4EdYDMq/fBclDBPmHE8gqxi721WrPAFxcZlHft8aRxJJfffLaSa+vOszO8paa4Hz+kLZrhwgzwVpiniA1DJpieK9MCH3T6JB9UWWA7xj/xUpYNdw+pCM3VshEsKy8kOeOZauv3nEZCIo//PpjjQSt0gqEIZwxplPAxp0V2JxCqKi2nceI8SZBkON+h1fxJkLqGc835qvjeXxOxPC2ZRnSyTyfHhBXWs/A8K59M9daSjBYTbAfO4vp3hO08L0l0ZIYbfz4DX084FJdCFCADSOyB2FtzNu+3cAysQuRwK1yxXGzA1fQpTB4611Q
    signing.key: AgCzAVmKqj67xFRjIVEaN9h3T7R7XrdFdmrwITjtJs8YQDjsAI2rRKJ6LZAPab9RZIMdUPmi7P4xWTHY3ogyCbJHoa533Kd9yUNwHZpf5KkVLxmXW0P2Zozx3d+sK3h59jTC1KOk233L94WLWUoPaTi/RiCcu/kmLqElLo296hUanWTj/gx4bQdOgFFP4LgUgnJzvPULtmRI+mJQFCtkEKVqyBHe7W5YP+9ZPc3pLF7GFNN7Ac5FNl1DDdCCJ/ZOVU10Of7VoaGYXoyhGLOuNghYaKOK8FUOaFOzt2iun5ukTqOL1SEe9uGlQkhxfTNmyF6RGoyuSwEHeJAjROwznjJ0+eIFTpYfnUCrjPA8+KQppRefltT5de+mwXz0GutsQvsQJFXPXM4bFjyKNtnWToKysAAQG8H/SF1wCi6vbdkq2D9E+/EEpDL5lj4WJ5mPAUcosZOHwUoXK5b8F84PB/xh3HOsZR+XPQzWWHntnOH3XuQ3+nacVdC7VIBaz3sbP/KZY93k77mU2TtgxgiW6T2uOX/F1P/TSdfzP2671LUjlD26QsGWyxzO2fRFDHk1neHXF6pfPJCZrVOgeZPVV0zxL3gaa9ec3q0vkcSC3hY0+lmkJKmLPbHG7ujS8Y7Jx6M7+GdaGswIA78AihqKu3csBN0I2TdQXTEkz3eWNYbCOzmeUnrwl1Vz1VskkWAg8mnda6mPCSbr8JCvrUVLpuUtz1frBlMKP9n3ZEx3Q84EV8fOeInExv4sKmdSX1wJY2HA3bJS4+ua04qYwA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: extraconfig
      namespace: chat
    data:
      extraConfig: |
        max_upload_size: 100M
        old_signing_keys:
          - '{{ index . "signing.key" }}'
        oidc_providers:
          - idp_id: oelleguard
            idp_name: Ølleguard
            discover: true
            issuer: https://auth.nikolaiathome.com
            authorization_endpoint: https://auth.nikolaiathome.com/oauth/v2/authorize
            token_endpoint: https://auth.nikolaiathome.com/oauth/v2/token
            userinfo_endpoint: https://auth.nikolaiathome.com/oidc/v1/userinfo
            client_id: 214037595124990002@nikolaiathome
            client_secret: '{{ index . "client_secret" }}'
            backchannel_logout_enabled: true
            scopes:
              - "openid"
              - "profile"
              - "email"
