---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: registrationsharedsecret
  namespace: chat
spec:
  encryptedData:
    registrationsharedsecret: AgBxdQIbyf9lZnctYpeea1m8uQdrY82hg294XgGnG69NLMakrMztEFTTZc0ynDLxXYFiSX5RO849Qxq2mUK21leYhJcM4OGDncgWkqenZqp1GCTPteZtJAywQstHszvT1uAkfP20kBb5cyXcuNjLHlTlG/9HeAz0iKqupaOWsvLkGXJB8eNGdgsI/mZ6v8Y70TBZH+E6X3PRFFu4Z+ufCCI4GtBNmFGjy2OnTdSNvPaM1fzkWE/YKSt06tpJCHh4e2/Zu/fANGxIO/UkIh7DPMRpsHkcI6YL54ZvDeDoReoR4pxyF4y6QJivz8mIGVmtT7I2OIExEhrpPvXSDh5D4z5CvlroOHsu29mQKC65WxgcqKzsu0UhW7gpuHGNAsncIjxFQnccNeX4+sRWSZ6Fjwonf519GrHWXgu7DXPXLtvL3UOjOuZNo7WqRdjKakWmWeRfjoVxddazTewaWyOpmv4FmMRm0rCEzSyaKfYShFmPn2kUJwnfSVGb26ZondRu3W2TvoaM43YLx1HZPVY8QVUUPYehQVaklB84YaPITlpKxHve8yT3s2Zaye2hgjxr7vZUAKSqpzI1lcccUWBU4drbU4fsDPRvjxz/Lp43VIpZChwDwIuz1FZaZdOZwVsMQbdFKUQS6pYhgKyf86IcVSl2KuxHfpdkRvzkK5fDTJQ6gpHLewBmmLnltPNIHLI4QxDGV4hnmXgdlOKPyz4wEwKXGApxHFcxcL0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: registrationsharedsecret
      namespace: chat
