apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: chat
spec:
  interval: 1m
  chart:
    spec:
      chart: matrix-synapse
      version: 3.2.8
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: chat
      interval: 1m
  values:
    image:
      repository: matrixdotorg/synapse
      tag: v1.83.0
    wellknown:
      enabled: true
    publicServerName: matrix.nikolaiathome.com
    serverName: nikolaiathome.com
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "X-Forwarded-Proto $scheme";
          more_set_headers "X-Forwarded-For   $proxy_add_x_forwarded_for";
  valuesFrom:
    - kind: Secret
      name: synapse-postgres-password
      valuesKey: password
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: synapse-redis-password
      valuesKey: password
      targetPath: redis.password
    - kind: Secret
      name: synapse-oauth-app
      valuesKey: oicd_providers
