apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-data
  namespace: chat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
