apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: chat
spec:
  interval: 1m
  chart:
    spec:
      chart: matrix-synapse
      version: 3.9.11
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: chat
      interval: 1m
  values:
    image:
      repository: ghcr.io/element-hq/synapse
      tag: v1.114.0
    wellknown:
      enabled: true
      client:
        m.homeserver:
          base_url: https://matrix.nikolaiathome.com/
        org.matrix.msc3575.proxy:
          url: https://syncv3.example.com
    publicServerName: matrix.nikolaiathome.com
    serverName: nikolaiathome.com
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
    extraConfig:
      max_upload_size: 100M
    synapse:
       resources:
        limits:
          cpu: 200m
          memory: 350Mi
        requests:
          cpu: 150m
          memory: 250Mi
  valuesFrom:
    - kind: Secret
      name: synapse-postgres-password
      valuesKey: password
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: synapse-redis-password
      valuesKey: password
      targetPath: redis.auth.password
    - kind: Secret
      name: synapse-oauth-app
      valuesKey: oicd_providers
