apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: matrix-synapse
  namespace: chat
spec:
  interval: 1m
  chart:
    spec:
      chart: matrix-synapse
      # renovate: datasource=helm depName=ananace-charts/matrix-synapse
      version: 3.9.11
      sourceRef:
        kind: HelmRepository
        name: ananace-charts
        namespace: chat
      interval: 1m
  values:
    # renovate: datasource=github-releases depName=element-hq/synapse
    appVersion: 1.128.0
    image:
      repository: ghcr.io/element-hq/synapse
      # renovate: datasource=github-releases depName=element-hq/synapse
      tag: v1.128.0
    wellknown:
      enabled: true
    publicServerName: matrix.nikolaiathome.com
    serverName: nikolaiathome.com
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 100m
    synapse:
       resources:
        limits:
          cpu: 500m
          memory: 500Mi
        requests:
          cpu: 150m
          memory: 250Mi
    postgresql:
      primary:
        persistence:
          storageClass: longhorn
  valuesFrom:
    - kind: Secret
      name: synapse-postgres-password
      valuesKey: password
      targetPath: postgresql.postgresqlPassword
    - kind: Secret
      name: synapse-redis-password
      valuesKey: password
      targetPath: redis.auth.password
    - kind: Secret
      name: extraconfig
      targetPath: extraConfig
      valuesKey: extraConfig
    - kind: Secret
      name: registrationsharedsecret
      valuesKey: registrationsharedsecret
      targetPath: config.registrationSharedSecret

