apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zitadel
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: zitadel
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: auth
      interval: 30m
      version: 4.3.0
  valuesFrom:
  - kind: ConfigMap
    name: zitadel-config-14-05-2023
    valuesKey: zitadel-values-14-05-2023.yaml
  - kind: Secret
    name: zitadel.db.user
    valuesKey: password
    targetPath: zitadel.secretConfig.Database.cockroach.User.Password
