apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zitadel
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: zitadel
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: auth
      interval: 30m
      version: 4.3.0
  values:
    image:
      repository: ghcr.io/zitadel/zitadel
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v2.23.1"
    zitadel:
      configmapConfig:
        ExternalSecure: false
        TLS:
          Enabled: false
      masterkeySecretName: "zitadel-masterkey"
    replicaCount: 1
    ingress:
      enabled: true
      hosts:
        - host: auth.nikolaiathome.com
          paths:
            - pathType: Prefix
              path: /
