apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- auth-namespace.yaml
- auth-source.yaml
- sealed-zitadel-masterkey.yaml
- sealed-zitadel.db.user.yaml
- auth-helmrelease.yaml


# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: zitadel-config-14-05-2023
  namespace: auth
  files:
  - zitadel-values-14-05-2023.yaml

generatorOptions:
  disableNameSuffixHash: true
