apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# declare ConfigMap as a resource
resources:
- auth-source.yaml
- auth-helmrelease.yaml
- auth-namespace.yaml
- sealed-zitadel-masterkey.yaml
- sealed-zitadel.db.user.yaml

# declare ConfigMap from a ConfigMapGenerator
configMapGenerator:
- name: zitadel-config
  namespace: auth
  files:
  - zitadel-values.yaml
