apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
configMapGenerator:
  - name: zitadel-values
    files:
      - values.yaml=zitadel-values.yaml
configurations:
  - kustomizeconfig.yaml
