image:
      repository: ghcr.io/zitadel/zitadel
      # Overrides the image tag whose default is the chart appVersion.
      tag: "v2.23.1"
zitadel:
  configmapConfig:
    ExternalSecure: false
    TLS:
      Enabled: false
  masterkeySecretName: "zitadel-masterkey"
replicaCount: 1
