apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: readlater
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/app: readlater
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
