apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: readlater
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
