apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: "22.6.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      interval: 15s
  values:
    alertmanager: # useful to recieve alerts if receiver you want is supported - see https://prometheus.io/docs/alerting/latest/configuration/#receiver
      enabled: false
    kube-state-metrics: #  Add-on agent to generate and expose cluster-level metrics. 
      enabled: true
    prometheus-node-exporter: #  Exporter for machine metrics 
      enabled: true
    prometheus-pushgateway: #  Push acceptor for ephemeral and batch jobs. 
      enabled: true
    server:
      image:
        repository: quay.io/prometheus/prometheus
        tag: v2.44.0 
