apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: paperless
spec:
  interval: 15m
  chart:
    spec:
      chart: paperless
      version: 5.1.1
      sourceRef:
        kind: HelmRepository
        name: pascaliske
        namespace: paperless
  values:
    # renovate: datasource=github-releases depName=paperless-ngx/paperless-ngx
    appversion: 2.18.2
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
    env:
      - name: TZ
        value: "Europe/Copenhagen"
      - name: PAPERLESS_URL
        value: "https://paperless.nikolaiathome.com"
    persistentVolumeClaim:
      storageClassName: longhorn
      size: 5Gi
    redis:
      enabled: true
