apiVersion: v1
kind: Service
metadata:
  name: etcd-cluster
  namespace: coredns
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
    - name: peer
      port: 2380
      targetPort: 2380
