apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kro:controller
  annotations:
    kubernetes.io/description: |
      This ClusterRole grants access for the kro controller.
      The kro installation comes with enough for the controller to run, and start watching the relevant resources
      (e.g. ResourceGraphDefinitions), but in order to allow kro to create and manage other types of resources you
      must manually grant access to those separately.
      The easiest way to accomplish this is to create a new ClusterRole with the label `rbac.kro.run/aggregate-to-controller: "true"`
      which will be automatically aggregated into this one.
  labels:
    app.kubernetes.io/name: kro
    app.kubernetes.io/instance: kro
    app.kubernetes.io/part-of: kro
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.kro.run/aggregate-to-controller: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kro:controller:static
  annotations:
    kubernetes.io/description: |
      This ClusterRole grants access for the kro controller to resources it always needs access to.
  labels:
    app.kubernetes.io/name: kro
    app.kubernetes.io/instance: kro
    app.kubernetes.io/part-of: kro
    rbac.kro.run/aggregate-to-controller: "true"
rules:
  - apiGroups:
      - kro.run
    resources:
      - resourcegraphdefinitions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kro.run
    resources:
      - resourcegraphdefinitions/finalizers
    verbs:
      - update
  - apiGroups:
      - kro.run
    resources:
      - resourcegraphdefinitions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - internal.kro.run
    resources:
      - graphrevisions
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - internal.kro.run
    resources:
      - graphrevisions/finalizers
    verbs:
      - update
  - apiGroups:
      - internal.kro.run
    resources:
      - graphrevisions/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kro:controller:app-template
  labels:
    rbac.kro.run/aggregate-to-controller: "true"
rules:
  - apiGroups:
      - kro.run
    resources:
      - applications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kro.run
    resources:
      - applications/status
      - applications/finalizers
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kro:controller
  labels:
    app.kubernetes.io/name: kro
    app.kubernetes.io/instance: kro
    app.kubernetes.io/part-of: kro
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: kro:controller
subjects:
  - kind: ServiceAccount
    name: kro
    namespace: kro-system
