apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kro:controller:app-template
  labels:
    rbac.kro.run/aggregate-to-controller: "true"
rules:
  - apiGroups:
      - kro.run
    resources:
      - applications
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - kro.run
    resources:
      - applications/status
    verbs:
      - get
      - patch
      - update
