apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kro
  namespace: kro-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kro
      version: ""
      sourceRef:
        kind: OCIRepository
        name: kro
        namespace: kro-system
      interval: 1m
