apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: manyfold
  namespace: 3dfiles
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: 3dfiles
  values:
    # renovate: datasource=github-releases depName=manyfold3d/manyfold
    appversion: 0.111.2
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/manyfold3d/manyfold-solo
              # renovate: datasource=github-releases depName=manyfold3d/manyfold
              tag: 0.111.2
            env:
              MULTIUSER: enabled
              PUID: "1000"
              PGID: "1000"
          filebrowser:
            image:
              repository: docker.io/hurlenko/filebrowser
              # renovate: datasource=github-releases depName=hurlenko/filebrowser-docker
              tag: v2.32.0
    service:
      main:
        controller: main
        ports:
          http:
            port: 3214
      filebrowser: 
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
        enabled: true
        hosts:
          - host: "3dfiles.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main 
                  port: http
    persistence:
      config:
        enabled: true
        existingClaim: config
        advancedMounts:
          main:
            filebrowser:
              - path: /data/config
            main: 
              - path: /config
      libraries:
        enabled: true
        existingClaim: libraries
        advancedMounts:
          main:
            filebrowser:
              - path: /data/libraries
            main: 
              - path: /libraries
  valuesFrom:
    - kind: Secret
      name: manyfold-secret-key
      valuesKey: manyfold-secret-key
      targetPath: controllers.main.containers.main.env.SECRET_KEY_BASE
