apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: manyfold
  namespace: 3dfiles
spec:
  name: manyfold
  namespace: 3dfiles
  container:
    image: ghcr.io/manyfold3d/manyfold-solo
    # renovate: datasource=github-releases depName=manyfold3d/manyfold
    tag: 0.126.0
    port: 3214
  url: "3dfiles.nikolaiathome.com"
  replicas: 1
  ingress:
    enabled: true
  externalVolumes:
    - name: config
      persistentVolumeClaim: config
      containerMountPath: /config
    - name: libraries
      persistentVolumeClaim: libraries
      containerMountPath: /libraries
  env:
    MULTIUSER: "enabled"
    PUID: "1000"
    PGID: "1000"
  envFromSecrets:
    SECRET_KEY_BASE:
      secretName: manyfold-secret-key
      valuesKey: manyfold-secret-key
  filebrowser:
    enabled: false
    port: 3926
  resources:
    memory: "1Gi"
    cpu: "0.25"
  runAsUser: 0
  runAsNonRoot: false
  livenessProbePath: "/"
  readOnlyRootFilesystem: false
