apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libraries
  namespace: 3dfiles
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
