apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: libraries
  namespace: 3dfiles
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/app: manyfold
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
