apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: grocy
  values:
    controller:
      type: statefulset
    image:
      repository: quay.io/linuxserver.io/grocy
      tag: 3.3.2
    env:
      TZ: "Europe/Copenhagen"
      GROCY_CULTURE: "da"
      GROCY_CURRENCY: "DKK"
      GROCY_AUTH_CLASS: Grocy\Middleware\ReverseProxyAuthMiddleware
      GROCY_REVERSE_PROXY_AUTH_HEADER: x-auth-request-preferred-username
      PUID: "1000"
      PGID: "1000"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        hosts:
          - host: "grocy.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
          nginx.ingress.kubernetes.io/auth-response-headers: Authorization
          nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers x-auth-request-preferred-username nikolaioellegaard;
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 2Gi
    persistence:
      php-conf:
        enabled: true
        type: configMap
        name: php-conf
        mountPath: /config/php
      viewcache:
        enabled: true
        type: emptyDir
        mountPath: /config/data/viewcache
    resources:
      requests:
        cpu: 22m
        memory: 164M
      limits:
        memory: 262M
