apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: grocy
  values:
    appVersion: 4.2.0
    controller:
      type: statefulset
    image:
      repository: quay.io/linuxserver.io/grocy
      tag: "4.2.0"
    env:
      TZ: "Europe/Copenhagen"
      GROCY_CULTURE: "da"
      GROCY_CURRENCY: "DKK"
      PUID: "1000"
      PGID: "1000"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        hosts:
          - host: "grocy.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
    persistence:
      php-conf:
        enabled: true
        type: configMap
        name: php-conf
        mountPath: /config/php
      viewcache:
        enabled: true
        type: emptyDir
        mountPath: /config/data/viewcache
      config:
        enabled: true
        mountPath: /config
        type: persistentVolumeClaim
        existingClaim: grocy-config-pvc
    resources:
      requests:
        cpu: 0.5
        memory: 264M
      limits:
        memory: 662M
