apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config-pvc
  namespace: grocy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
