apiVersion: v1
kind: ConfigMap
metadata:
  namespace: grocy
  name: php-conf
data:
  www2.conf: |
    ; Edit this file to override www.conf and php-fpm.conf directives and restart the container

    ; Pool name
    [www]
    clear_env = no
  php-local.ini: |
    ; Edit this file to override php.ini directives

    date.timezone = Europe/Copenhagen
