apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
spec:
  interval: 30m
  chart:
    spec:
      chart: grocy
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: grocy
      interval: 30m
      version: 8.5.2
  values: 
    persistence:
      grocy.db:
        enabled: true
        type: pvc
        size: 1Gi
        mountPath: /config/data/grocy.db      
    env:
      # -- Set the container timezone
      TZ: Europe/Copenhagen 
      GROCY_CURRENCY: DKK
    image:
      # -- image repository
      repository: linuxserver/grocy
      # -- image tag
      # @default -- chart.appVersion
      tag: 3.3.2
      # -- image pull policy
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        hosts:
          - host: "grocy.nikolaiathome.com"
            paths:
              - path: "/"
