apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: grocy
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: grocy
      interval: 30m
      version: 6.12.0
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.4.0
    config:
      existingSecret: grocy-oauth2-credentials
      configFile: |-
        provider = "oidc"
        provider_display_name = "Ølleguard"
        oidc_issuer_url = "https://auth.nikolaiathome.com"
        email_domains = [ "*" ]
        scope = "openid profile email"
        whitelist_domains = ".nikolaiathome.com"
        pass_authorization_header = true
        pass_access_token = true
        pass_user_headers = true
        set_authorization_header = true
        set_xauthrequest = true
        cookie_refresh = "1m"
        cookie_expire = "30m"
    ingress:
      enabled: true
      path: /oauth2
      hosts:
        -  "grocy.nikolaiathome.com"
      annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "x-auth-request-preferred-username nikolaioellegaard";