apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: grocy
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: grocy
      interval: 30m
      version: 6.12.0
  values:
    image:
      repository: quay.io/oauth2-proxy/oauth2-proxy
      tag: v7.4.0
    config:
      existingSecret: grocy-oauth2-credentials
    ingress:
      enabled: true
      hosts:
        -  "oauth.grocy.nikolaiathome.com"
