apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockroachdb
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: cockroachdb
      sourceRef:
        kind: HelmRepository
        name: cockroachdb
        namespace: auth
      interval: 30m
      version: 10.0.10
  values: 
    fullnameOverride: crdb
    image:
      repository: cockroachdb/cockroach
      tag: v22.2.9
      registry: docker.io
    conf:
      single-node: true
    statefulset:
      replicas: 1
    persistentVolume:
      persistentVolume:
        storageClass: local-path
