apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cockroachdb
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: cockroachdb
      sourceRef:
        kind: HelmRepository
        name: cockroachdb
        namespace: auth
      interval: 30m
      version: 12.0.5
  values: 
    fullnameOverride: crdb
    image:
      repository: cockroachdb/cockroach
      tag: v22.2.9
      registry: docker.io
    conf:
      single-node: true
    statefulset:
      securityContext:
        enabled: false
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi
    persistentVolume:
      persistentVolume:
        storageClass: local-path
    tls:
      certs:
        selfSigner:
          enabled: true
        certManager: true
        certManagerIssuer:
          kind: Issuer
          name: cockroachdb
