apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extensions
  namespace: rss
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
