apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-volume
  namespace: music
  labels:
    name: music-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
