apiVersion: kro.run/v1alpha1
kind: Application
metadata:
  name: music
  namespace: music
spec:
  name: music
  namespace: music
  container:
    image: deluan/navidrome
    # renovate: datasource=github-releases depName=navidrome/navidrome
    tag: 0.58.0
    port: 4533
  url: "music.nikolaiathome.com"
  replicas: 1
  ingress:
    enabled: true
  volumes:
    - name: data
      persistentVolumeClaim: navidrome-data-volume
      containerMountPath: /data
    - name: music
      persistentVolumeClaim: music-volume
      containerMountPath: /music
  env:
    TZ: "Europe/Copenhagen"
    PUID: "5000"
    PGID: "5000"
    ND_PORT: "4533"
    ND_BASEURL: "https://music.nikolaiathome.com"
    ND_ENABLESHARING: "true"
    ND_ENABLEGRAVATAR: "true"
    ND_DEFAULTTHEME: "CatppuccinMacchiato"
    ND_LASTFM_ENABLED: "true"
  envFromSecrets:
    ND_SPOTIFY_SECRET:
      secretName: spotify-client
      valuesKey: clientsecret
    ND_SPOTIFY_ID:
      secretName: spotify-client
      valuesKey: clientid
    ND_LASTFM_SECRET:
      secretName: lastfm-api
      valuesKey: apisharedsecret
    ND_LASTFM_APIKEY:
      secretName: lastfm-api
      valuesKey: apikey
  filebrowser:
    enabled: true
    port: 3923
  resources:
    memory: 300Mi
    cpu: 25m
