apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-volume
  namespace: music
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
