apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-volume
  namespace: music
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
