apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: music
  values:
    controller:
      type: statefulset
    image:
      repository: deluan/navidrome
      # renovate: datasource=docker depName=docker.io/deluan/navidrome
      tag: "0.51.1"
    env:
      TZ: "Europe/Copenhagen"
      PUID: "5000"
      PGID: "5000"

    service:
      main:
        ports:
          http:
            port: 4533

    ingress:
      main:
        enabled: true
        hosts:
          - host: "music.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
    persistence:
      music:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
      data:
        enabled: true
        type: pvc
    resources:
      requests:
        cpu: 22m
        memory: 164Mi
      limits:
        memory: 262Mi
