apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: music
  values: 
    appVersion: 0.52.5
    controller:
      type: statefulset
    image:
      repository: deluan/navidrome
      # renovate: datasource=docker depName=docker.io/deluan/navidrome
      tag: "0.52.5"
    env:
      TZ: "Europe/Copenhagen"
      PUID: "5000"
      PGID: "5000"
      ND_PORT: 80
      ND_BASEURL: "https://music.nikolaiathome.com"
      ND_ENABLESHARING: true
      ND_ENABLEGRAVATAR: true
      ND_DEFAULTTHEME: "CatppuccinMacchiato"
      ND_LASTFM_ENABLED: true

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        hosts:
          - host: "music.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
    persistence:
      music:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 20Gi
      data:
        enabled: true
        accessMode: ReadWriteOnce
        size: 2Gi
        type: pvc
    resources:
      requests:
        cpu: 22m
        memory: 164Mi
      limits:
        memory: 262Mi
  valuesFrom:
    - kind: Secret
      name: lastfm-api
      valuesKey: apikey
      targetPath: env.ND_LASTFM_APIKEY
    - kind: Secret
      name: lastfm-api
      valuesKey: apisharedsecret
      targetPath: env.ND_LASTFM_SECRET
