apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 1m
  chart:
    spec:
      chart: navidrome
      version: 0.0.6
      sourceRef:
        kind: HelmRepository
        name: 0xemma
        namespace: music
      interval: 1m
  values:
    image:
      repository: deluan/navidrome
      tag: 0.51.1
    ingress:
      main:
        enabled: true
        hosts:
          - host: music.nikolaiathome.com
            paths:
              - path: /
                pathType: Prefix
