apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: music
  values: 
    appVersion: 0.56.1
    controllers:
      main:
        type: statefulset
        pod: 
          securityContext:
            fsGroup: 5000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: deluan/navidrome
              # renovate: datasource=docker depName=docker.io/deluan/navidrome
              tag: "0.56.1"
            securityContext:
              runAsUser: 5000
              runAsGroup: 5000
            env:
              TZ: "Europe/Copenhagen"
              PUID: "5000"
              PGID: "5000"
              ND_PORT: 80
              ND_BASEURL: "https://music.nikolaiathome.com"
              ND_ENABLESHARING: true
              ND_ENABLEGRAVATAR: true
              ND_DEFAULTTHEME: "CatppuccinMacchiato"
              ND_LASTFM_ENABLED: true
          filebrowser:
            image:
              repository: docker.io/hurlenko/filebrowser
              # renovate: datasource=github-releases depName=hurlenko/filebrowser-docker
              tag: v2.32.0
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
      filebrowser: 
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          # add an annotation indicating the issuer to use.
          cert-manager.io/cluster-issuer: cloudflare-issuer
        hosts:
          - host: "music.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
                service:
                  identifier: main
                  port: http 
        tls:
          - hosts:
            - music.nikolaiathome.com
            secretName: music-nikolaiathome-com-http-tls
    persistence:
      music:
        existingClaim: music-volume
        advancedMounts:
          main:
            main:              
              - path: /music
            filebrowser:              
              - path: /data/music
      data:
        existingClaim: navidrome-data-volume
        advancedMounts:
          main:
            main:              
              - path: /data
            filebrowser:              
              - path: /data/data
    resources:
      requests:
        cpu: 22m
        memory: 164Mi
      limits:
        memory: 262Mi
  valuesFrom:
    - kind: Secret
      name: lastfm-api
      valuesKey: apikey
      targetPath: controllers.main.containers.main.env.ND_LASTFM_APIKEY
    - kind: Secret
      name: lastfm-api
      valuesKey: apisharedsecret
      targetPath: controllers.main.containers.main.env.ND_LASTFM_SECRET
    - kind: Secret
      name: spotify-client
      valuesKey: clientid
      targetPath: controllers.main.containers.main.env.ND_SPOTIFY_ID
    - kind: Secret
      name: spotify-client
      valuesKey: clientsecret
      targetPath: controllers.main.containers.main.env.ND_SPOTIFY_SECRET
