apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: music
  values: 
     # renovate: datasource=github-releases depName=navidrome/navidrome
    appVersion: 0.57.0
    controllers:
      main:
        type: statefulset
        pod: 
          securityContext:
            fsGroup: 5000
            fsGroupChangePolicy: OnRootMismatch
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet

        containers:
          main:
            image:
              repository: deluan/navidrome
              # renovate: datasource=github-releases depName=navidrome/navidrome
              tag: 0.57.0
            securityContext:
              runAsUser: 5000
              runAsGroup: 5000
            env:
              TZ: "Europe/Copenhagen"
              PUID: "5000"
              PGID: "5000"
              ND_PORT: 4533
              ND_BASEURL: "https://music.nikolaiathome.com"
              ND_ENABLESHARING: true
              ND_ENABLEGRAVATAR: true
              ND_DEFAULTTHEME: "CatppuccinMacchiato"
              ND_LASTFM_ENABLED: true
          filebrowser:
            image:
              repository: docker.io/copyparty/ac
              # renovate: datasource=github-releases depName=9001/copyparty
              tag: 1.18.6
    service:
      main:
        controller: main
        ports:
          http:
            port: 4533
      filebrowser: 
        controller: main
        ports:
          http:
            port: 3923
    ingress:
      main:
        enabled: true
        annotations:
          # add an annotation indicating the issuer to use.
          cert-manager.io/cluster-issuer: cloudflare-issuer
        hosts:
          - host: "music.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
                service:
                  identifier: main
                  port: http 
        tls:
          - hosts:
            - music.nikolaiathome.com
            secretName: music-nikolaiathome-com-http-tls
    persistence:
      music:
        existingClaim: music-volume
        advancedMounts:
          main:
            main:              
              - path: /music
            filebrowser:              
              - path: /w
      data:
        existingClaim: navidrome-data-volume
        advancedMounts:
          main:
            main:              
              - path: /data
      copyparty-config:
        enabled: true
        type: configMap
        name: copyparty-config
        advancedMounts:
          main:
            filebrowser:
              - path: /cfg
    resources:
      requests:
        cpu: 22m
        memory: 164Mi
      limits:
        memory: 262Mi
  valuesFrom:
    - kind: Secret
      name: lastfm-api
      valuesKey: apikey
      targetPath: controllers.main.containers.main.env.ND_LASTFM_APIKEY
    - kind: Secret
      name: lastfm-api
      valuesKey: apisharedsecret
      targetPath: controllers.main.containers.main.env.ND_LASTFM_SECRET
    - kind: Secret
      name: spotify-client
      valuesKey: clientid
      targetPath: controllers.main.containers.main.env.ND_SPOTIFY_ID
    - kind: Secret
      name: spotify-client
      valuesKey: clientsecret
      targetPath: controllers.main.containers.main.env.ND_SPOTIFY_SECRET
