apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: navidrome
  namespace: music
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: music
  values: 
    appVersion: 0.52.5
    controllers:
      main:
        type: statefulset
        pod: 
          securityContext:
            fsGroup: 5000
            fsGroupChangePolicy: OnRootMismatch
        containers:
          main:
            image:
              repository: deluan/navidrome
              # renovate: datasource=docker depName=docker.io/deluan/navidrome
              tag: "0.53.3"
            securityContext:
              runAsUser: 5000
              runAsGroup: 5000
    env:
      TZ: "Europe/Copenhagen"
      PUID: "5000"
      PGID: "5000"
      ND_PORT: 80
      ND_BASEURL: "https://music.nikolaiathome.com"
      ND_ENABLESHARING: true
      ND_ENABLEGRAVATAR: true
      ND_DEFAULTTHEME: "CatppuccinMacchiato"
      ND_LASTFM_ENABLED: true

    service:
      main:
        controller: main
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        hosts:
          - host: "music.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
                service:
                  identifier: main
                  port: http 
    persistence:
      music:
        existingClaim: music-volume
        globalMounts:
          - path: /music
      data:
        existingClaim: navidrome-data-volume
        globalMounts:
          - path: /data
    resources:
      requests:
        cpu: 22m
        memory: 164Mi
      limits:
        memory: 262Mi
  valuesFrom:
    - kind: Secret
      name: lastfm-api
      valuesKey: apikey
      targetPath: env.ND_LASTFM_APIKEY
    - kind: Secret
      name: lastfm-api
      valuesKey: apisharedsecret
      targetPath: env.ND_LASTFM_SECRET
    - kind: Secret
      name: spotify-client
      valuesKey: clientid
      targetPath: env.ND_SPOTIFY_ID
    - kind: Secret
      name: spotify-client
      valuesKey: clientsecret
      targetPath: env.ND_SPOTIFY_SECRET
