apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: video
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: video
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/jellyfin/jellyfin
      tag: 10.8.13
    service:
      main:
        ports:
          http:
            port: 8096
    ingress:
      main:
        enabled: true
        hosts:
          - host: "video.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      media:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Gi
      config:
        enabled: true
        mountPath: /config
        type: pvc
        accessMode: ReadWriteOnce
        size: 100Gi
      cache:
        enabled: true
        mountPath: /cache
        type: pvc
        accessMode: ReadWriteOnce
        size: 50Gi
      dri:
        enabled: true
        hostPath: /dev/dri
        type: hostPath
    securityContext:
      supplementalGroups:
        - 122 # Change this to match your "render" host group id (taken from `getent group render | cut -d: -f3`)
