apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: video
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: video
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.8.13
      service:
        main:
          ports:
            http:
              port: 8096
              protocol: HTTP
    ingress:
      main:
        enabled: true
        hosts:
          - host: "video.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        accessMode: ReadWriteOnce
        size: 50Gi
        advancedMounts:
          main:
            main:
              - path: /config
                subPath: jellyfin/config
              - path: /media/movies
                subPath: movies
              - path: /media/shows
                subPath: shows
