apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: video
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: video
  values:
    # renovate: datasource=github-releases depName=jellyfin/jellyfin
    appversion: 10.10.7
    controllers:
      main:
        type: statefulset
        pod: 
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              # renovate: datasource=github-releases depName=jellyfin/jellyfin
              tag: 10.10.7
          filebrowser:
            image:
              repository: docker.io/copyparty/ac
              # renovate: datasource=github-releases depName=9001/copyparty
              tag: 1.19.9
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
      filebrowser: 
        controller: main
        ports:
          http:
            port: 3924
    ingress:
      main:
        enabled: true
        annotations:
          # add an annotation indicating the issuer to use.
          cert-manager.io/cluster-issuer: cloudflare-issuer
        hosts:
          - host: "video.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main 
                  port: http
        tls:
          - hosts:
            - video.nikolaiathome.com
            secretName: video-nikolaiathome-com-http-tls
    resources:
      requests:
        cpu: 2
        memory: 450M
      limits:
        memory: 1000M
    persistence:
      video-volume:
        enabled: true
        existingClaim: video-volume
        advancedMounts:
          main:
            filebrowser:
              - path: /w
            main: 
              - path: /media
      jellyfin-db-volume:
        enabled: true
        existingClaim: jellyfin-db-volume
        advancedMounts:
          main:
            main: 
              - path: /config
      jellyfin-server-cache:
        enabled: true
        existingClaim: jellyfin-server-cache
        advancedMounts:
          main: 
            main: 
              - path: /cache
      dri:
        enabled: true
        hostPath: /dev/dri
        type: hostPath
      copyparty-config:
        enabled: true
        type: configMap
        name: copyparty-config
        advancedMounts:
          main:
            filebrowser:
              - path: /cfg

