apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: video
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: video
  values:
    # renovate: datasource=github-releases depName=jellyfin/jellyfin
    appversion: 10.9.8
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: docker.io/jellyfin/jellyfin
              # renovate: datasource=github-releases depName=jellyfin/jellyfin
              tag: 10.9.8
          filebrowser:
            image:
              repository: docker.io/hurlenko/filebrowser
              # renovate: datasource=github-releases depName=hurlenko/filebrowser-docker
              tag: v2.32.0
    service:
      main:
        controller: main
        ports:
          http:
            port: 8096
      filebrowser: 
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: "video.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main 
                  port: http
    persistence:
      video-volume:
        enabled: true
        existingClaim: video-volume
        advancedMounts:
          main:
            filebrowser:
              - path: /data/video-volume
      jellyfin-db-volume:
        enabled: true
        existingClaim: jellyfin-db-volume
        advancedMounts:
          main:
            filebrowser:
              - path: /data/jellyfin-volume
      jellyfin-server-cache:
        enabled: true
        existingClaim: jellyfin-server-cache
        advancedMounts:
          main: 
            filebrowser:
              - path: /data/jellyfin-cache
      media:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        advancedMounts:
          main: 
            main: 
              - path: /media
            filebrowser:
              - path: /data/media
        size: 100Gi
      config:
        enabled: true
        advancedMounts:
          main: 
            main: 
              - path: /config
            filebrowser:
              - path: /data/config
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
      cache:
        enabled: true
        advancedMounts:
          main: 
            main: 
              - path: /cache
            filebrowser:
              - path: /data/cache
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 50Gi
      dri:
        enabled: true
        hostPath: /dev/dri
        type: hostPath
