apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-volume
  namespace: video
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1500Gi
