apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 1m
  chart:
    spec:
      chart: rook-ceph
      version: 1.13.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-cluster
        namespace: rook-ceph
      interval: 30m
  values:
    cephClusterSpec:
      cephVersion:
        image:
          repository: quay.io/ceph/ceph:v18.2.2
      mon:
        count: 1 # Generally recommended to be 3, but it's one node people!
        allowMultiplePerNode: false
      mgr:
        count: 1
        allowMultiplePerNode: false
    monitoring:
      enabled: true
    ingress:
      dashboard:
        host:
           name: ceph-dashboard.nikolaiathome.com
           path: /
