apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook
  namespace: rook-ceph
spec:
  interval: 1m
  chart:
    spec:
      chart: rook-ceph
      version: 0.0.6
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 30m
  values:
    image:
      repository: rook/ceph
      tag: v1.13.7
    monitoring:
      enabled: true
