apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: writefreely
  namespace: blog
spec:
  interval: 30m
  chart:
    spec:
      chart: writefreely
      sourceRef:
        kind: HelmRepository
        name: writefreely
        namespace: blog
      interval: 30m
      version: 1.0.0
  values: 
    image:
      repository: ghcr.io/nicholaswilde/writefreely
      tag: "version-0.13.1"
    ingress:
      enabled: true
      hosts:
        - host: blog.nikolaiathome.com
          paths:
            - pathType: Prefix
              path: /
  valuesFrom:
  - kind: Secret
    name: writefreely-config
    valuesKey: config
    targetPath: config
