apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: writefreely
  namespace: blog
spec:
  interval: 30m
  chart:
    spec:
      chart: writefreely
      sourceRef:
        kind: HelmRepository
        name: writefreely
        namespace: blog
      interval: 30m
      version: 1.0.0
  valuesFrom:
  - kind: Secret
    name: writefreely-config
    valuesKey: config.ini
  - kind: ConfigMap
    name: writefreely-helm-values
