apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gatus-sidecar-config
  namespace: health
  labels:
    name: gatus-sidecar-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi

