apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCD055VA54OsRwNF+zVng8j4cEEVr9DAXONTTlxqSzCM+edIaRI/mJ/L/BF0aAqhV7oPT8r4w2OhuBb+0M5cYAS+5z34VxONC1PeQpjssZAdnAMGNrY/mbcSCny2B4uqHvt90QzTH+fqC4LbpOx/eIf6HEpFXNO87P8dzUaUvKCFZKZElXMvmPXTAH3vec3hbr59nFZLpWCVQko3V+03qpz+UvGxUGz9DYWJfKTSckwxdmWMeStjEPVNzYkt2GfDWmo13MXpfXab4cS7qVPRYDp0KcVBgI/+4c8csaRQwjJPIr/QLQyUB/8SuKltOfQfSPMO+wRDZry01tQ8QMOLsrTpr3woCb0cX5TQAb471yqtpYjdLPqJB3M05SRIMbNXai7aRz7UD3fwGmjKuGCzp+E90CH9R3PSPP0apK6BdIxm/AzyfGZClR0rgYyvTTtFhxswwujB5uQ2XqiUqoUzfEqcv2TTqIjcznojyPuCeX2CjiUU0WUm09bsEXwxdDvNR7WJfxLwxpm+RnZ1oSoMJNSWmJHHkQONFv3GzSirQR/XAKW+7dTwUA1hvGwfwEopfWOtw3l/xl0jcPR+TqQJSf56ToMRO/Foh+NYGUrEu/Cyjm7aNb+xHSQoPtaJzbVJj1EL5KNpGndG4uywRJRZROaYX8ol3T73FWTgFykpAz9qZwlA2Y5etWmg8IGarSTZU24OfncV1c8zfJ40BWW1RdNFGJYJHQcBHEcoI0W6yGcfMwHoAoqksfZATdGzSM+y2y4OVEQBbaDyKfXmskcLh6TzQtjBgfvDWnSnmkBtFLiiLjdYqqCd2gM5D0UGGJjVF1n3sBOW4ZbKhIgwIsAe8LFy+aekEv2nQB7qWBHfPqptQYFuL6ZMJk+jSNihFFchLMs09JCn5NLxdZEI40vkABcjw==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default

