apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobook
  namespace: audiobook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
