apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcast
  namespace: audiobook
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/app: audiobook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
