apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nikolai@oellegaard.com
    privateKeySecretRef:
      name: letsencrypt-staging
    # Add a single challenge solver, HTTP01
    solvers:
    - http01:
        ingress: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nikolai@oellegaard.com
    privateKeySecretRef:
      name: letsencrypt
    # Add a single challenge solver, HTTP01 
    solvers:
    - http01:
        ingress:
          class: haproxy

