apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: garage
  namespace: garage
spec:
  interval: 15m
  url: https://git.deuxfleurs.fr/Deuxfleurs/garage
  ref:
    branch: main-v1
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/script/helm/ 
