apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-coredns
  namespace: external-dns
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
      interval: 5m
  values:
    fullnameOverride: external-dns-coredns
    provider:
      name: coredns
    extraArgs:
      - --coredns-prefix=/skydns/
    env:
      - name: ETCD_URLS
        value: http://etcd-cluster.coredns.svc.cluster.local:2379
    triggerLoopOnEvent: true
    policy: sync
    sources:
      - ingress
      - service
    txtOwnerId: fleet
    txtPrefix: k8s.fleet.-
    domainFilters:
      - nikolaiathome.com
      - local.nikolaiathome.com
    serviceMonitor:
      enabled: false
