---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unifi-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    UNIFI_API_KEY: AgAEx9vIhU2IGv90+ia3bLEjvKep8Da+RUO4hZmWaVuoxsCuSwm2oRFMsLfcCJy22ENEpm2kLb2UAyjPznQgJv2Ci0VFebb8K/yQhseM/b1Suc+aLtcFOE1xLxymWaV4/XH749nHzCY3cY2+cZc3HWYZtayFJAfwRTMyWMsaUKA8vpojrd2y2KtnqzyR6eBdYTnvrxk+aYCAiOX+MVfiM5V5PEIX/bvFv0TjbGLz1S2ombv+CPdCvpD91P86AAaSsg3He/GZqEGR4LMN4/IjeGX1C190XUZoaoMtTkVflJ1FSPotljxb8ypto7IyvOp0DnSpKgC5g22YGhzaOX1LsghlX7hdlxiuBXYb9tMZVke+2VdeaXtQJtKzeLaejEM11jRf0HSwIhhJL6lvHl+q/S6rOuCGHGH7JQX3gUchwJ3gW/aOvH6Mo230rJv0W3gWow6jjZaOAlrsAHoMnQAMgH+Iim16MEpafGnJ9z7VsU/mY4VYSe68dj3/wNadSLLYOHW7L2qt7hZSuACFXp7dTp4GeRmF9afnoiEGFppYMDH3G5Sl8YKTWF3z3n5+TQHn21twcFEBzRXkm+yRU8TV/c8E9g5ciDHm3y5FmTWNerJuMrvYkc7nPcRqqyXodZl1Ar1Q110XTjzquyRkVW+MGE4siZAHWNsGZPbjDr8PEDDBfrB36S2zPllquoS1wqNLIGCaIdSt1XuPMFkOOl9iaq4LqKZ2Cm+NO3NkVhgjKprUzA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unifi-dns-secret
      namespace: external-dns
