---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unifi-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    UNIFI_API_KEY: AgBuTuWscOZC5dBO92WXNmypABtDTJn4mmwxghJZlxUAJFvTuYMDlMJjApq6s7Uc1P5IEYFXdAehgvaD4Tjy14e/itCGiZhBLzeV5gsJC0bKh2sX4kRrXj/fj/smifvhM5XpHPxghQ11N0ZpYpCzA4oqPkCVk0/31QUnuxcSh/3hnrKS7ulN95Bia7z/+QHpcm15r6umZtmjLsCIbre1qx52ytVbJFCcef0/CAYVX9wbwytzfeSWxx8tvHSfBh7Z/dHiane9UnISVMwJz3caBoUwjlk61lDvwOdAdJggJecaQWUbSzYW6G6wDZcC4R/179T3kAHwDtCiyQKl1Hq+COKJKGBS/lXjFvswhU3l74RpwUjehu4eb2ouPOkHAopQyj/F5ivuZecpWh5Cu1X0xO8pHGiiJ8qDO/hr6eC+TynA0QGxssXxZtgRgV/IXSBcrNAlRkOD1n9MsjVl5+pWSTwg7pShwwtg8rgBeqd95vbnMoI0YCP7Js5VEI+nKgXeDk0DC2uevc4+Q1Opz9Q6TkbSJHIHn3UI/tpEBihPlUm3rUqtR3V0CfcxQhBLWJ3aRXiH0pKwn/tACqT/hcA7RlqdNzjcHdlO8/CpMkhqF88mZ/pZ5xb56jH47dqVbROOEUZ3iujTPhQqPMTRn3qdZckJCCZTnBhAE0pebwO6GTN3LVj3wwNpj1SVoptZ5dmbPhTMaN9Y0Sy8IWy5Ps7KhacBrTxfuHTXM1G/sypkwfRXNg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unifi-dns-secret
      namespace: external-dns
