---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: unifi-dns-secret
  namespace: external-dns
spec:
  encryptedData:
    UNIFI_API_KEY: AgA4Qj4ucUhGWNtSRoojnmTpU5uYILnG5GhZlbzKr/x4Ou9YaXBVfHUBJ/8GYU1++bwKbgvG2NgnWv8TPcpVYbmRYekx+8cQNauSO5p+9grG9wSiRdzystKMIsfTW+pb/nK2IhGCuRAM7VnSg3fo64Nd2iufCwWNXa4CBFbe0U1D8ZBREg6EZ9mMbS0kzyYAylvlpGn7XzOhYil8gpKd8tHLFypAb8lrQThrxFbNzzflPG/hvpDmKLo6/J/HBTgtTDGJPJJfFYOR1zwx6DEydpNUiurf5irXrcX4H7szAqu1YZ6+0q8hFS6I4Ph2Uzw8F9Gz0fzIvnNYQ8lyXYcFFH1fVkxAYCDi6LBe34bV2bvW9NEWFe38u47D29FP8/KxGCUHZHQAb9g/u+3G8OO1ILCYESqCIE0J3AKgma0gwKT0Yp1N6Yt//x2CG7FmgAmaUMXFm1HLkQ6XvfwZInXjn05NYj0wxRoqQbSr2Wdc2mOMaDULpCAzNANlZbd0/lvjop+3qeDCpqSr3ipn7lYVRoEL8e4mZnvvnUISLnivwFQ3u7gsS2TZgHwCT5fv5qWQPovLfakY6S0uORs6BvuRy++FUYlkLGL1xysiSgaU+upMD3+j1+GXQYrmWae/TYWKKVVShgbPlLur8ZZgo/dSpYo4lftS8YY2x39n8QsVMbqK+57vcbKpYRsThi5Y1fGc3EDrIsjkC3agT36FKZPZHcAXdfcFYH6/gaxbprpaGsZ0xA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: unifi-dns-secret
      namespace: external-dns
    type: Opaque
