apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: writefreely-config
  namespace: writings
spec:
  encryptedData: {}
  template:
    metadata:
      creationTimestamp: null
      name: writefreely-config
      namespace: writings
    data:
      config.ini: |
        [server]
        hidden_host = 
        port        = 8080
        bind = 0.0.0.0
        [database]
        type = sqlite3
        username = user
        password = writefreely
        database = writefreely2
        filename
        ; host = db
        ; port     = 3306
        [app]
        site_name         = Nikolais writings!
        host              = https://writings.nikolaiathome.com
        theme             = write
        disable_js         = false
        webfonts          = true
        single_user       = true
        open_registration    = false
        min_username_len  = 3
        max_blogs         = 1
        federation        = true
        public_stats       = true
        private           = false
        update_checks     = true
