apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: writefreely-config
  namespace: writings
spec:
  encryptedData:
    ClientSecret: AgCetdYY6k5/8ZuHZAftom1CtSTFRyMFFx6rt98bIRg6UmWUCcmB+ObtSfaUj+triFbsZZ0LwPN2SPJtIVwz/fedz1bndIZivG9xMMwVjs1NKjMNZILbZ2inHSE4WCa0fRLNBpOj/qKHa2OpGxxOGS+duv2eNvpM8CVh6qLzDBT4REFfRzSYE7fRXYwEF9v8T3X2Sz3vvIJlb4llnvW3XMbLDZkxDRs+t6XGXvpw9wGpuK2wAYi563gllBTG87hvxETkOHB3gSNGGcJdsVbcgIyeLnT7bOo8PshyF1SQc59+4x1g9sZENaO9oaV2GUHcGnrbAqs+CihrWbVTQlsqIdtNCMz3kRtbeycgzOZl6LrK5VucgIL1XGDE3UPp7OK9P/Syadl6HGwOUngek2r22HS5JdR0A0RvrRAcDb4uxRjLiQW1A+gOB5hj+qRDTB5QxcEskDr56TeGrVHjvJzN/HbF8SrYun02zsUdlHGRv/VMfxrixoNSylvVoM88nxn5s5vEy/YyNDDxPLXoYsYUL/JbGrflKQUdhjBpef2pB3Z7m6jI9BEYQVJ/SMjjb+RGHrC8Qn1d6BB9IduB8R0TgzjNUu4qUucvX42Y9iusk93KTgVrP8D6UuH6G3qxx/WJm5bO9MC45dNRE9XSsLqY7RwGgVAegjKwyY/erL4fwo6JkIQ/M1fTPkhjVcn3BzGOlSrn1eE9VS13NZ9o2cA/gvEziEf/ePWcezeNowensUC9Sn5z0hqmSSPwJogzv/3CckgRriJe865jA+SOH5Hh4t/B
  template:
    metadata:
      creationTimestamp: null
      name: writefreely-config
      namespace: writings
    data:
      config.ini: |
        [server]
        hidden_host          = 
        port                 = 80
        bind                 = 0.0.0.0
        tls_cert_path        = 
        tls_key_path         = 
        autocert             = false
        templates_parent_dir = /writefreely
        static_parent_dir    = /writefreely
        pages_parent_dir     = /writefreely
        keys_parent_dir      = 
        hash_seed            = 
        gopher_port          = 0

        [database]
        type     = sqlite3
        filename = /data/writefreely.db
        username = 
        password = 
        database = 
        host     = localhost
        port     = 3306
        tls      = false

        [app]
        site_name             = Nikolais writings!
        site_description      = where I write about things
        host                  = https://writings.nikolaiathome.com
        theme                 = write
        editor                = 
        disable_js            = false
        webfonts              = true
        landing               = 
        simple_nav            = false
        wf_modesty            = false
        chorus                = false
        forest                = false
        disable_drafts        = false
        single_user           = false
        open_registration     = true
        open_deletion         = false
        min_username_len      = 3
        max_blogs             = 0
        federation            = true
        public_stats          = true
        monetization          = false
        notes_only            = false
        private               = false
        local_timeline        = false
        user_invites          = 
        default_visibility    = 
        update_checks         = false
        disable_password_auth = true

        [oauth.slack]
        client_id          = 
        client_secret      = 
        team_id            = 
        callback_proxy     = 
        callback_proxy_api = 

        [oauth.writeas]
        client_id          = 
        client_secret      = 
        auth_location      = 
        token_location     = 
        inspect_location   = 
        callback_proxy     = 
        callback_proxy_api = 

        [oauth.gitlab]
        client_id          = 
        client_secret      = 
        host               = 
        display_name       = 
        callback_proxy     = 
        callback_proxy_api = 

        [oauth.gitea]
        client_id          = 
        client_secret      = 
        host               = 
        display_name       = 
        callback_proxy     = 
        callback_proxy_api = 

        [oauth.generic]
        client_id          = 216202172960931856@nikolaiathome
        client_secret      = {{ index . "ClientSecret" }}
        host               = https://auth.nikolaiathome.com
        display_name       = Ølleguard
        callback_proxy     = 
        callback_proxy_api = 
        token_endpoint     = /oauth/v2/token
        inspect_endpoint   = /oidc/v1/userinfo
        auth_endpoint      = /oauth/v2/authorize
        scope              = openid profile read_user
        allow_disconnect   = false
        map_user_id        = sub
        map_username       = preferred_username
        map_display_name   = name
        map_email          = email
