apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: writings
  namespace: writings
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: writings
  values:
    controller:
      type: statefulset
    image:
      repository: algernon/writefreely
      # renovate: datasource=docker depName=docker.io/algernon/writefreely
      tag: "0.13.2-2"
    env:
      TZ: "Europe/Copenhagen"
      PUID: "5000"
      PGID: "5000"

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        hosts:
          - host: "writings.nikolaiathome.com"
            paths:
              - path: /
                pathType: Prefix  
    persistence:
      data:
        enabled: true
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
      config:
        enabled: true
        type: secret
        name: writefreely-config
        subPath: config.ini
        mountPath: /home/config.ini
        readOnly: true
    resources:
      requests:
        cpu: 22m
        memory: 164M
      limits:
        memory: 262M
    initContainers:
      copy-config:
        image: alpine:3.17
        imagePullPolicy: Always
        command: ["cp", "/home/config.ini", "/data/config.ini"]
        volumeMounts:
        - name: config
          mountPath: /home/config.ini
          subPath: config.ini
        - name: data
          mountPath: /data
