apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: writefreely-data-volume
  namespace: writings
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
