apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd
  namespace: node-feature-discovery
spec:
  interval: 1m
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
