apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: cockroachdb
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
      interval: 30m
      version: 1.14.5
  values: 
    installCRDs: true
