---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    token: AgA+R3GYHKyUr7/PmtUYsDWUFJhkcmtoM7qosyYD/jAn5PIi7Ut0UuvFocAzaQL9BI5+L4G8gj1OUYlPQHGxMOpPTVXh7WGs/ggRANCNc0CwxYdpWObFvE3P5tjo+QioNIdWaVCaVq3b6EoZPfu52I/WQ7MC1sKppur8Qv87YmSvTFjwAbQN61yaSp8ADF0bp17vkbm8f0bKfkgRz9CuLyJA3xeH4y9BdseJcdZJ1VfzQedz6jarXvJ9S/YKHywn+LyEZc5bxbjH0n4e2u/0hRrAkOzrNWG0Eiy+SYWnrtUgxNgoj/CQHCETO6Mto7H7n5GCqIYdbsrDCCK0ZJTA8BiSUNTFiLtkMpbpAaKxUPq+qH/6jNnzWJURIKDiZYCXOdnvFcmGLC7YnvApFqAV5270oI/hK3uh4GPCypzw9E3xpwaib2dtqpkqI/UN26Pnhs6USCiAWiNmY2JOYA+wExihZXN0kuxI01OH3cXxtnRgKtAbf7W0qTQcTyjknSXH1aCpAFLoMGVsBUcWYK7us+b+UmQzOtL/HEYmX0V7THg/J4C960DysC80+Q5DiRUsTVGSdB7uQ4G5nE3+dn0uCqxgnjjy58XnEv7cKU0fHUu1Kj7T/AKP0Psh5sXaU8ej1QKcAP3PWdo5K/KtuEUsOuDMIIu4P+mJQRs8MUPQxbH2ScSlP1L+zuCgQWIDTGFFP0/DWOusdlMHBFZIZ1cfzNcHpRWWMA1bFtyZg0fy+DX0CCVtNkNJloXG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
